/*
 *  this file is part of Game Categories Lite
 *
 *  Copyright (C) 2011  Codestation
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "stub_macro.s"

CREATE_STUB add_vsh_item_stub
CREATE_STUB execute_action_stub
CREATE_STUB unload_module_stub
CREATE_STUB paf_get_text_stub
CREATE_STUB get_page_node_stub
CREATE_STUB resolve_ref_wstring_stub
CREATE_STUB get_registry_stub
CREATE_STUB set_registry_stub
CREATE_STUB xmb_push_stub
CREATE_STUB xmb_context_stub
CREATE_STUB display_context_stub
//CREATE_STUB menu_scroll_stub
